<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ConsoleApp</AssemblyName>
    <RootNamespace>ConsoleApp</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="secrets.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="secrets.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Challenge\Challenge.csproj" />
  </ItemGroup>

</Project>
